FROM systemd_rawhide
### CDIC START, code until tag `CDIC END` was auto-generated by cdic service

RUN yum install -y dnf dnf-plugins-core \
    && mkdir -p /etc/yum.repos.d/
RUN dnf copr enable -y msychy/copr
RUN dnf clean all

### CDIC END
RUN yum -y install httpd copr-frontend; yum clean all; systemctl enable httpd.service
EXPOSE 80
CMD [“/usr/sbin/init”]
